### PR TITLE
Clean-up README (#80)

### LINKED ISSUE #80: Update README
- [x] 1. The current logo on cpp-linter-action is different from the logo on Org's home page. I prefer to move the old one.
- [x] ~~2. Add an example snip about how to use cpp-linter as a package with other CI tools, like Jenkins. and which arguments they can not use.~~ Will update the new repo of cpp-linter when it supports on-GitHub-based CI, and this repo is only used for github action.
- [x] ~~3. Replace the second used by with chocolate-doom~~
- [x] 4. Remove old [and more](https://github.com/search?q=shenxianpeng%2Fcpp-linter-action&type=Code) link
- [x] 5. Remove Gitpod badge. it not very necessary and it appears as two lines on the marketplace page https://github.com/marketplace/actions/c-c-lint-action

### PR DESCRIPTION
**Pull request by shenxianpeng**
Resolve #80

### CODE REVIEW

**Review by 2bndy5 — APPROVED** [review]
I guess this should be titled "clean-up README" 😄

**Comment by 2bndy5** [comment]
Was the icon_large.xcf file (my GIMP project) moved to the .github repo?

**Comment by shenxianpeng** [comment]
> Was the icon_large.xcf file (my GIMP project) moved to the .github repo?

Sure, what icon_large.xcf used for?

**Comment by 2bndy5** [comment]
> what is icon_large.xcf used for? 

I do all my image manipulation using [GIMP](https://www.gimp.org/). I used the xcf file to save my work on the favicon we've been using:
image

Personally, I like how the yellow circle looks better in dark theme. The current icon is a bit bland in dark theme:
image

**Comment by shenxianpeng** [comment]
En, yellow should look good in both dark and default themes, the pre-commit icon is also yellow, but our yellow icon is not sharp enough why I want to remove it, see https://github.com/cpp-linter/cpp-linter-action/blob/894a54988abed9f2c7a37f5b54694e819de7f462/docs/images/icon_large.png 

If the new yellow icon could display well(sharp and lossless) as the current icon, we can change to yellow.  https://github.com/cpp-linter/cpp-linter-action/blob/894a54988abed9f2c7a37f5b54694e819de7f462/docs/images/icon.png

**Comment by 2bndy5** [comment]
oh,
1. I added a slight bevel (with shadow) to the circle so the checkmark would pop out.
2. I also added a shadow to the check mark to make it seem 3D layered.
3. There is some slight pixelation around the edges because I scaled it up a bit to reduce the empty space around it. Then I tried to hide that with some bevel shadows.

If you're looking for flat, that's easy.
image

**Comment by shenxianpeng** [comment]
This yellow circle icon looks great 👍 I would also like to see the flat

**Comment by 2bndy5** [comment]
I still don't like the empty space around it, but when I scale it up, it gets pixelated.
image

What did you use to create the logo?

**Comment by shenxianpeng** [comment]
I found the logo from google or Canva, I forgot it 😟

**Pull request merged**
